# Generated by Django 3.1.3 on 2020-11-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puppy',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='puppy',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='puppy',
            name='age',
            field=models.CharField(max_length=255),
        ),
    ]
